# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 334a446a9d0cf3c56ecabfdd4417d7b023988448d116f4044bb40c5bdce2f18327f4bb0eccfb235a86e893526d2662deaed620912568914b5f2e6e0d57bc922d

test:
  secret_key_base: d9d7bc958568c2ab4d6ef7dc36f4fb71adf7c7040a6624dbf540b10b20bf4af8bdf70a51149d134e831adc72b487cd7155e278a64102617842a749c60b56400f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
